[build]
# dossier de publication pour Vite
publish = "/dist"
# commande pour construire l'application
command = "npm install && npm run build"

[[redirects]]
# rediriger toutes les requêtes /api vers Railway
from = "/api/*"
to = "https://ton-backend-railway.up.railway.app/:splat"
status = 200
force = true

[[redirects]]
# rediriger toutes les autres requêtes vers index.html pour React Router
from = "/*"
to = "/index.html"
status = 200
